# Permalinks
permalink:           pretty
future: false

# Setup
title:               'Brian Whitman'
url:                 https://bwhitman.github.io
#tagline:             Hi
paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""
markdown: kramdown 

# Includes
include:
  - _redirects

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Brian Whitman
  url:               https://twitter.com/bwhitman
  email:             brian@variogram.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/bwhitman/taunt-jekyll

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
